import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { classNames } from "~/utils/classNames";
import Sidebar from "./Sidebar";
import PageHeader from "./PageHeader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main
      className={classNames(inter.className, "flex items-start bg-primary")}
    >
      <aside className="flex min-h-[100svh] flex-col gap-6 bg-primary">
        <Sidebar />
      </aside>
      <div className="relative z-10 flex h-full min-h-screen w-full  flex-col gap-4 rounded-bl-2xl rounded-tl-2xl bg-background p-4">
        <PageHeader />
        {children}
      </div>
    </main>
  );
}
